{{- if and .Values.secrets (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nafa-service.fullname" . }}
  labels:
    {{- include "nafa-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
